In [2]:
import numpy as np

In [6]:
a = np.array([1,0,3,-1])
print(a)

[ 1  0  3 -1]


In [12]:
a = np.ndarray((2,3))
for x in range(a.shape[0]):
    print(x)


0
1


In [46]:
a = np.arange(10)
print(a)
print(np.concatenate((a[:2], a[5:])))


[0 1 2 3 4 5 6 7 8 9]
[0 1 5 6 7 8 9]


In [50]:
b = np.zeros((3,5))
print(b.shape[0])

3
