In [84]:
import numpy as np
import collections
import sklearn.preprocessing
#from scipy.special import softmax
import scipy.special

In [7]:
x = np.arange(10)
print(x)
x = x.reshape(2,5)
print(x)
x = x.reshape(5,2)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [26]:
x = np.arange(3*7*5)
x = x.reshape(3,7,5)
print(x)
x = np.rot90(x, axes=(1,2))
print(x)
print(x.shape)
x = np.flip(x, 1)
print(x)
print(x.shape)

[[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25  26  27  28  29]
  [ 30  31  32  33  34]]

 [[ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]
  [ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]]

 [[ 70  71  72  73  74]
  [ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]
  [100 101 102 103 104]]]
[[[  4   9  14  19  24  29  34]
  [  3   8  13  18  23  28  33]
  [  2   7  12  17  22  27  32]
  [  1   6  11  16  21  26  31]
  [  0   5  10  15  20  25  30]]

 [[ 39  44  49  54  59  64  69]
  [ 38  43  48  53  58  63  68]
  [ 37  42  47  52  57  62  67]
  [ 36  41  46  51  56  61  66]
  [ 35  40  45  50  55  60  65]]

 [[ 74  79  84  89  94  99 104]
  [ 73  78  83  88  93  98 103]
  [ 72  77  82  87  92  97 102]
  [ 71  76  81  86  91  96 101]
  [ 70  75  80  85  90  95 100]]]
(3, 

In [80]:
a = np.array([[[0,1,0,0,0],[1,0,0,0,0],[0,0,0,1,0]],[[0,0,1,0,0],[0,0,0,0,1],[1,0,0,0,0]]])
b = np.array([[[0,1,0,0,0],[1,0,0,0,0],[0,0,1,0,0]],[[0,0,1,0,0],[0,0,0,0,1],[0,1,0,0,0]]])
print(a)
print('\n')
print(b)
nul = np.array([ 0,  0,  0,  0,  0])

[[[0 1 0 0 0]
  [1 0 0 0 0]
  [0 0 0 1 0]]

 [[0 0 1 0 0]
  [0 0 0 0 1]
  [1 0 0 0 0]]]


[[[0 1 0 0 0]
  [1 0 0 0 0]
  [0 0 1 0 0]]

 [[0 0 1 0 0]
  [0 0 0 0 1]
  [0 1 0 0 0]]]


In [93]:
dif = a-b
unique, counts = np.unique(dif, return_counts=True)
x = dict(zip(unique, counts))
print(x)
print(x[0])
#print(dif.flatten())
#x = collections.Counter(dif.flatten())
#print(x)

{-1: 2, 0: 26, 1: 2}
26
